apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- Backend/deploy.yml
- Backend/service.yml
- Frontend/deploy.yml
- Frontend/service.yml


images:
- name: 749856334984.dkr.ecr.us-east-1.amazonaws.com/app/backend
  newName: 749856334984.dkr.ecr.us-east-1.amazonaws.com/app/backend
  newTag: b4c475b4e481e7e8b362ef0fd5ea183e4f41c353
- name: 749856334984.dkr.ecr.us-east-1.amazonaws.com/app/frontend
  newName: 749856334984.dkr.ecr.us-east-1.amazonaws.com/app/frontend
  newTag: 20afec54fbc56095688ae086b155cf8c1dfb10b0
