apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- Backend/deploy.yml
- Backend/service.yml
- Frontend/deploy.yml
- Frontend/service.yml

images:
- name: 749856334984.dkr.ecr.us-east-1.amazonaws.com/app/backend
  newName: 749856334984.dkr.ecr.us-east-1.amazonaws.com/app/backend
  newTag: v1.0

- name: 749856334984.dkr.ecr.us-east-1.amazonaws.com/app/frontend
  newName: 749856334984.dkr.ecr.us-east-1.amazonaws.com/app/frontend
  newTag: v1.0
 